before_install:
  - chmod +x gradlew

notifications:
    slack: korbasoftware:cX8FwzEugFfCbagL2EfgZEjw

language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    - organization: korbasoftware
    - token:
        secure: 862646087ffb0752a2db8d1fac16297e0c3b367a
script:
  gradle check
