before_install:
  - chmod +x gradlew

notifications:
    slack: korbasoftware:cX8FwzEugFfCbagL2EfgZEjw

dist: trusty

language: java

jdk:
  - oraclejdk8


addons:
  sonarcloud:
    organization: "fryc1906-github"
    branches:
        - fryc-sonarIntegration
        - master
    token:
        - "3c80a23fbc1d2a25d3a808c0babed7333d017e80"
    github_token:
        - "fdeb4eb181f51e23e5d880a734b88c9cb4e0759a"



script:
  - sonar-scanner -X

  

