before_install:
  - chmod +x gradlew

notifications:
    slack: korbasoftware:cX8FwzEugFfCbagL2EfgZEjw
    
language: java
sudo: false
install: true
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "korba"
    token: "77b860d6d3d2add156cd1a5477eb2c8ab912c123"
      #secure: "your_token_encrypted_with_travis_encrypt_tool"

script:
  - ./gradlew sonarqube
  - sonar-scanner
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
