before_install:
  - chmod +x gradlew

notifications:
    slack: korbasoftware:cX8FwzEugFfCbagL2EfgZEjw

dist: trusty

language: java
jdk:
  - oraclejdk8


addons:
  sonarcloud:
    organization: "korbasoftware"
    branches:
        - fryc-sonarIntegration
        - master
    token:
        - "862646087ffb0752a2db8d1fac16297e0c3b367a"
    github_token:
        - "fdeb4eb181f51e23e5d880a734b88c9cb4e0759a"



script:
  - sonar-scanner
  - ./gradlew sonarqube -Dsonar.organization=korbasoftware -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=862646087ffb0752a2db8d1fac16297e0c3b367a
  

