before_install:
  - chmod +x gradlew

notifications:
    slack: korbasoftware:cX8FwzEugFfCbagL2EfgZEjw

language: java
jdk:
  - oraclejdk8


addons:
  sonarcloud:
    organization: "korbasoftware" # the key of the org you chose at step #3
    token:
      secure: SONAR_TOKEN # encrypted value of your token


sonarqube:
    branches :
    - fryc-sonarIntegration
    - master

script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  - gradle check

