before_install:
  - chmod +x gradlew

notifications:
    slack: korbasoftware:cX8FwzEugFfCbagL2EfgZEjw

language: java
jdk:
  - oraclejdk8

addons:
  sonarqube: true
env:
  global:
    - secure: <the token generated on sonarqube.com>
script:
  gradle check